### ISSUE TITLE
Btrfs-progs need to be installed.

### ISSUE THREAD

**Issue by Luke-Nukem** [mrgreen3/archbang#1]
Hey there. Used your iso recently to install Arch.
I used a set-up consisting of LVM on LUKS, with Btrfs for the file system. Only issue I had was I needed to manually install the btrfs-progs.

Just a heads up :)

**Comment by mrgreen3** [comment]
Ok will add them to next release, thanks for letting me know ...


On Sunday, June 7, 2015, Luke Jones <notifications@github.com> wrote:

> Hey there. Used your iso recently to install Arch.
> I used a set-up consisting of LVM on LUKS, with Btrfs for the file system.
> Only issue I had was I needed to manually install the btrfs-progs.
>
> Just a heads up :)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mrgreen3/archbang/issues/1>.
>


-- 
Kev

**Comment by mrgreen3** [comment]
Added ;-)
